on: push

name: build_binder

jobs:
  build_binder:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create dependencies dir
        run: |
          mkdir -p /tmp/renv/cache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ipea/test:latest
          cache-from: type=local,src=/tmp/renv/cache
          cache-to: type=local,src=/tmp/renv/cache

      - name: List dependencies
        run: |
          ls /tmp/renv/cache
